kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "cephfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi